const actualitesData = [
  {
    "id": 4003,
    "title": "Atelier IPAS-FRAO-CNA : structurer la filière avicole pour une Afrique de l'Ouest souveraine",
    "slug": "/atelier-ipas-frao-cna-filiere-avicole-2025",
    "date": "01 Juil 2025",
    "year": "2025",
    "category": "Agriculture",
    "image": "assets/tof15.jpg",
    "excerpt": "Réunis à Mbao le 1er juillet 2025, les acteurs de l'aviculture ont validé la cartographie nationale du secteur et adopté une feuille de route vers une plateforme régionale multi-acteurs pour transformer durablement la filière.",
    "read_time_min": 6
  },
  {
    "id": 4002,
    "title": "Mballing : un projet pilote pour l'autonomisation économique des femmes par le séchage solaire",
    "slug": "/mballing-autonomisation-femmes-sechage-solaire",
    "date": "Jan 2026",
    "year": "2026",
    "category": "Genre",
    "image": "assets/mballing-1.jpeg",
    "excerpt": "La FRAO lance un projet pilote à Mballing (Sénégal) pour structurer une coopérative féminine de transformation de mangues séchées, combinant innovation technique et inclusion sociale pour créer des revenus durables.",
    "read_time_min": 4
  },
  {
    "id": 4001,
    "title": "Formation microfinance et mise en place du comité de gestion à Bonaba",
    "slug": "/formation-microfinance-comite-gestion-bonaba-2025",
    "date": "Sept 2025",
    "year": "2025",
    "category": "Agriculture",
    "image": "assets/bonaba-1.jpeg",
    "excerpt": "La FRAO, en partenariat avec Better World, a conduit une formation de 4 jours sur la microfinance auprès de 40 membres de la coopérative Agricom de Bonaba, débouchant sur la mise en place d'un comité structuré de gestion du microcrédit.",
    "read_time_min": 5
  },
  {
    "id": 3254,
    "title": "Atelier d’information et de sensibilisation sur les Coopératives du 24 au 26 Juillet 2024 à Bonaba avec l’ONG BETTER WORLD",
    "slug": "/atelier-dinformation-et-de-sensibilisation-sur-les-cooperatives-du-24-au-26-juillet-2024-a-bonaba-avec-long-better-world",
    "date": "08 Oct 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/leader1.jpg",
    "excerpt": "Atelier avec les leaders des associations, du GIE et avec les femmes et les jeunes\nTournée d’information et de...",
    "read_time_min": 4
  },
  {
    "id": 3237,
    "title": "Atelier au King Fahd Palace le 17 Avril 2024",
    "slug": "/atelier-au-king-fahd-palace-le-17-avril-2024",
    "date": "01 Oct 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "Le forum de partage et d’échanges avec les jeunes a pour objectif de présenter les réalisations et effet des...",
    "read_time_min": 6
  },
  {
    "id": 3229,
    "title": "Enquêtes sur l'engagement des Associations et du GIE",
    "slug": "/enquetes-sur-lengagement-des-associations-et-du-gie",
    "date": "30 Sep 2024",
    "year": "2024",
    "category": "Gouvernance",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Enquêtes sur l’engagement des Associations et du GIE à mettre en place une Coopérative du 07 au 13 Août 2024 a...",
    "read_time_min": 3
  },
  {
    "id": 3221,
    "title": "Atelier de partage et de consolidation des Résultats d’ADOS aux Résidences Mamoune",
    "slug": "/atelier-de-partage-et-de-consolidation-des-resultats-dados-aux-residences-mamoune",
    "date": "30 Sep 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/image1.jpg",
    "excerpt": "PROGRAMME ADOS : Amélioration de la Santé de la Reproduction des Adolescentes au SénégalAtelier de partage et de...",
    "read_time_min": 4
  },
  {
    "id": 3217,
    "title": "Atelier d’élaboration des Produits de Connaissances pour le Partage des résultats du Programme ADOS Hôtel Onomo du 18 au 19 Mars 2024",
    "slug": "/atelier-delaboration-des-produits-de-connaissances-pour-le-partage-des-resultats-du-programme-ados",
    "date": "28 Sep 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/cassava.jpg",
    "excerpt": "Cet atelier a pour objectifs de sélectionner les thèmes pour alimenter les premiers produits de connaissances ;...",
    "read_time_min": 6
  },
  {
    "id": 3026,
    "title": "cooperation between FRAO and SNU.",
    "slug": "/cooperation-between-frao-and-snu",
    "date": "24 Août 2023",
    "year": "2023",
    "category": "Genre",
    "image": "assets/tof10.jpg",
    "excerpt": "FRAO/WARF and Seoul National University.\nFRAO/WARF continues its partnership with Koica and Korean organizations. In...",
    "read_time_min": 8
  },
  {
    "id": 3022,
    "title": "Nouveau Conseil des Gouverneurs.",
    "slug": "/nouveau-conseil-des-gouverneurs",
    "date": "24 Août 2023",
    "year": "2023",
    "category": "Genre",
    "image": "assets/leader1.jpg",
    "excerpt": "La FRAO/WARF s'est dotée d'un nouveau Conseil des Gouverneurs (CG) en Février 2023. Ce changement fait suite à...",
    "read_time_min": 8
  },
  {
    "id": 2911,
    "title": "Agricultural Value Chain Interaction Platforms (AVIP)",
    "slug": "/agricultural-value-chain-interaction-platforms-avip",
    "date": "23 Nov 2021",
    "year": "2021",
    "category": "Climat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "To have more /click on the link below\nAgricultural Value Chain Interaction Platforms (AVIP)",
    "read_time_min": 3
  },
  {
    "id": 2824,
    "title": "Formation en «Gestion Administrative et Financière » des bénéficiaires du Projet de Développement communautaire de Better World à Bonaba",
    "slug": "/la-formation-en-gestion-administrative-et-financiere-des-beneficiaires-du-projet-de-developpement-communautaire-de-better-world-a-bonaba",
    "date": "17 Nov 2021",
    "year": "2021",
    "category": "Agriculture",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Du 04 au 06 octobre, s’est tenu une formation en «Gestion Administrative et Financière» organisée par l’ONG Better...",
    "read_time_min": 8
  },
  {
    "id": 2741,
    "title": "Agricultural Value Chain Interaction Platforms (AVIP) for Sustainable Access to Markets",
    "slug": "/agricultural-value-chain-interaction-platforms-avip-for-sustainable-access-to-markets",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Agriculture",
    "image": "assets/image1.jpg",
    "excerpt": "The ROOTS project, with implementation support from West Africa Rural Foundation, has initiated work on the...",
    "read_time_min": 7
  },
  {
    "id": 2728,
    "title": "Resilience of Organizations for Transformative Smallholder Agriculture Project (ROOTS)",
    "slug": "/resilience-of-organizations-for-transformative-smallholder-agriculture-project-roots",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Climat",
    "image": "assets/cassava.jpg",
    "excerpt": "The International Fund for Agricultural Development (IFAD) is supporting The Government of the Gambia to implement the...",
    "read_time_min": 8
  },
  {
    "id": 2725,
    "title": "Formation en « Dynamique Organisationnelle » des bénéficiaires du Projet de Développement communautaire de Better World à Bonaba",
    "slug": "/formation-en-dynamique-organisationnelle-des-beneficiaires-du-projet-de-developpement-communautaire-de-better-world-a-bonaba",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "24 bénéficiaires ont pris part aux trois jours de formation, organisés à l’intention des leaders du Groupement...",
    "read_time_min": 5
  },
  {
    "id": 2674,
    "title": "Collaboration entre la FRAO et BETTER WORLD pour le renforcement des capacités des bénéficiaires du Projet de Développement Communautaire à Bonaba)",
    "slug": "/collaboration-entre-la-frao-et-better-world-pour-le-renforcement-des-capacites-des-beneficiaires-du-projet-de-developpement-communautaire-a-bonaba",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Gouvernance",
    "image": "assets/leader1.jpg",
    "excerpt": "Le 27 Août 2021, les deux institutions ont signé un contrat de prestation de service pour l’exécution de sessions de...",
    "read_time_min": 5
  },
  {
    "id": 2644,
    "title": "Nécrologie: Décès du Docteur Dominique Hounkonnou.",
    "slug": "/necrologie-deces-du-docteur-dominique-hounkonnou",
    "date": "24 Nov 2020",
    "year": "2020",
    "category": "Gouvernance",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": ".",
    "read_time_min": 2
  },
  {
    "id": 2445,
    "title": "Visite d’échange des bénéficiaires du projet AVIP dans la vallée du fleuve Sénégal",
    "slug": "/visite-dechange-des-beneficiaires-du-projet-avip-dans-la-vallee-du-fleuve-senegal",
    "date": "14 Nov 2019",
    "year": "2019",
    "category": "Genre",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "La FRAO, depuis 2018, est l’acteur principal de la mise en œuvre du projet « Agricultural Value Chain Interaction...",
    "read_time_min": 2
  },
  {
    "id": 2439,
    "title": "Formation sur les plateformes d’interaction de la chaîne de valeur riz",
    "slug": "/formation-sur-les-plateformes-dinteraction-de-la-chaine-de-valeur-riz",
    "date": "11 Sep 2019",
    "year": "2019",
    "category": "Climat",
    "image": "assets/image1.jpg",
    "excerpt": "La FRAO a initié une série d’ateliers de formation sur les plateformes d’interaction de la chaine de valeur riz au...",
    "read_time_min": 6
  },
  {
    "id": 2380,
    "title": "Nouveau membre du staff programme .",
    "slug": "/nouveau-membre-du-staff-programme",
    "date": "02 Juil 2019",
    "year": "2019",
    "category": "Gouvernance",
    "image": "assets/cassava.jpg",
    "excerpt": "Serigne Tacko Kandji est titulaire d'un diplôme d'ingénieur agronome et d'un doctorat en agro-écologie.\nIl travaille en...",
    "read_time_min": 8
  },
  {
    "id": 2336,
    "title": "Pot de départ à la retraite",
    "slug": "/pot-de-depart-a-la-retraite",
    "date": "15 Juin 2019",
    "year": "2019",
    "category": "Agriculture",
    "image": "assets/tof10.jpg",
    "excerpt": "Le Conseil des Gouverneurs de la FRAO ainsi que sa Direction Exécutive ont rendu un vibrant hommage à Mme THIAM pour...",
    "read_time_min": 2
  },
  {
    "id": 2325,
    "title": "Activités de renforcement de capacités du mois de février 2019",
    "slug": "/activites-de-renforcement-de-capacites-du-mois-de-fevrier-2019",
    "date": "08 Avr 2019",
    "year": "2019",
    "category": "Gouvernance",
    "image": "assets/leader1.jpg",
    "excerpt": "Conformément au document de référence, la FRAO poursuit la mise en œuvre de l’an II du Projet relatif aux chaînes de...",
    "read_time_min": 3
  },
  {
    "id": 2270,
    "title": "Atelier à mi-parcours",
    "slug": "/atelier-a-mi-parcours",
    "date": "26 Fév 2019",
    "year": "2019",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "Cet atelier organisé, par la FRAO le 26 janvier 2019 dernier, avait pour objectif d’évaluer la mise en œuvre de la...",
    "read_time_min": 5
  },
  {
    "id": 2242,
    "title": "Journées d’échange et de dégustation  « Field Day »",
    "slug": "/journees-dechange-et-de-degustation-field-day",
    "date": "22 Jan 2019",
    "year": "2019",
    "category": "Agriculture",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Le « Field Day » est l’aboutissement des premières activités agronomiques mises en œuvre dans le cadre du Projet de...",
    "read_time_min": 2
  },
  {
    "id": 2199,
    "title": "Les premières récoltes de riz",
    "slug": "/les-premieres-recoltes-de-riz",
    "date": "05 Déc 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/image1.jpg",
    "excerpt": "Les récoltes dans les parcelles de démonstration rizicoles de Pendao 3 et de Dimath (Zone d'intervention du Projet de...",
    "read_time_min": 8
  },
  {
    "id": 2126,
    "title": "Sessions de Formation en « Irrigation et Protection des Cultures »",
    "slug": "/sessions-de-formation-en-irrigation-et-protection-des-cultures",
    "date": "04 Déc 2018",
    "year": "2018",
    "category": "Climat",
    "image": "assets/cassava.jpg",
    "excerpt": "Il s’agit de la troisième session de formation agronomique au profit des bénéficiaires du Projet de Développement...",
    "read_time_min": 4
  },
  {
    "id": 2115,
    "title": "Ateliers de formation sur la « Gouvernance dans la gestion d’un GIE »",
    "slug": "/ateliers-de-formation-sur-la-gouvernance-dans-la-gestion-dun-gie",
    "date": "19 Oct 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "Ces ateliers sont organisés par la FRAO à l’intention des Groupements d’Intérêt Economique (GIE) bénéficiaires du...",
    "read_time_min": 3
  },
  {
    "id": 2009,
    "title": "Ateliers de formation sur «l’Entretien des cultures du riz »",
    "slug": "/ateliers-de-formation-sur-lentretien-des-cultures-du-riz-2",
    "date": "11 Oct 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/leader1.jpg",
    "excerpt": "Ces ateliers sont organisés à la suite de la formation sur la Préparation d’une campagne rizicole et l’installation des...",
    "read_time_min": 8
  },
  {
    "id": 1995,
    "title": "Ateliers de formation sur les Techniques de Production Améliorées: Préparation de campagne et Installation des cultures",
    "slug": "/ateliers-de-formation-sur-les-techniques-de-production-ameliorees-preparation-de-campagne-et-installation-des-cultures",
    "date": "28 Sep 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "Dans le but de permettre aux producteurs d’améliorer leurs techniques de production rizicole, trois ateliers de...",
    "read_time_min": 8
  },
  {
    "id": 1988,
    "title": "Ateliers de formation en « Gestion Administrative et Financière des GIE »",
    "slug": "/ateliers-de-formation-en-gestion-administrative-et-financiere-des-gie",
    "date": "28 Sep 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "La FRAO a animé trois (03) ateliers de formation en « Gestion Administrative et Financière » dans le cadre de la mise...",
    "read_time_min": 3
  },
  {
    "id": 1983,
    "title": "Formation en « Dynamique Organisationnelle » des GIE et Unions bénéficiaires du Projet de Développement Durable et Inclusif de la Chaîne de Valeur Riz à Podor.",
    "slug": "/formation-en-dynamique-organisationnelle-des-gie-et-unions-beneficiaire-du-projet-de-developpement-durable-et-inclusif-de-la-chaine-de-valeur-riz-a-podor",
    "date": "28 Sep 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/image1.jpg",
    "excerpt": "La FRAO est responsable de la mise en œuvre du volet renforcement de capacités des Organisations Paysannes...",
    "read_time_min": 2
  },
  {
    "id": 1965,
    "title": "Ateliers de lancement communautaire du Projet de Développement Durable et Inclusif de Chaine de Valeur Riz à Podor",
    "slug": "/ateliers-de-lancement-communautaire-du-projet-de-developpement-durable-et-inclusif-de-chaine-de-valeur-riz-a-podor",
    "date": "18 Sep 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/cassava.jpg",
    "excerpt": "Pour l’opérationnalisation des activités du projet de Développement Durable et Inclusif de Chaine de Valeur Riz à...",
    "read_time_min": 7
  },
  {
    "id": 1855,
    "title": "Nécrologie : Une ancienne membre du Conseil des gouverneurs de la FRAO décédée",
    "slug": "/necrologie-une-ancienne-membre-du-conseil-des-gouverneurs-de-la-frao-decedee",
    "date": "09 Juil 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/tof10.jpg",
    "excerpt": "Hommage à une Militante\ndu développement durable et de l’autonomisation\ndes femmes en Afrique : Madame Diana Lima...",
    "read_time_min": 4
  },
  {
    "id": 1845,
    "title": "CONVENTION    DE    COLLABORATION FRAO- Fédération des Associations du Xer (FAX)",
    "slug": "/convention-de-collaboration-frao-federation-des-associations-du-xer-fax",
    "date": "05 Juil 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/leader1.jpg",
    "excerpt": "La FRAO, fidèle à sa mission de contribuer à résoudre les problèmes des sociétés rurales africaines, en appuyant les...",
    "read_time_min": 3
  },
  {
    "id": 1272,
    "title": "PARTENARIAT avec la FONDATION 2iE (Institut International d’Ingénierie de l’Eau et de l’Environnement)",
    "slug": "/partenariat-avec-la-fondation-2ie-institut-international-dingenierie-de-leau-et-de-lenvironnement",
    "date": "21 Fév 2018",
    "year": "2018",
    "category": "Climat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "La FRAO et la Fondation 2IE (Institut International d’Ingénierie de l’Eau et de l’Environnement) ont signé une...",
    "read_time_min": 6
  },
  {
    "id": 1243,
    "title": "Assistance technique au Ministère de la Pêche et de l’Aquaculture de (MPA) de la République du Congo.",
    "slug": "/assistance-technique-au-ministere-de-la-peche-et-de-laquaculture-de-mpa-de-la-republique-du-congo",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "La FRAO a signé un contrat d’assistance technique de huit (8) mois (Mai – Décembre 2016) pour le renforcement des...",
    "read_time_min": 2
  },
  {
    "id": 1239,
    "title": "Ateliers de formation du 2 au 6 mai 2016 – Accra, Ghana.",
    "slug": "/ateliers-de-formation-du-2-au-6-mai-2016-accra-ghana",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/image1.jpg",
    "excerpt": "Dans le cadre de l’Accord de Partenariat signé en Janvier 2015 avec Fondation 2iE Institut International d'Ingénierie...",
    "read_time_min": 2
  },
  {
    "id": 1230,
    "title": "Nouveau  Directeur Exécutif de la FRAO",
    "slug": "/nouveau-directeur-executif-de-la-frao",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/cassava.jpg",
    "excerpt": "Le Conseil des Gouverneurs de la Fondation, lors de sa session extraordinaire du 18 mars 2016, a retenu le Dr. Mohamed...",
    "read_time_min": 6
  },
  {
    "id": 1225,
    "title": "Document de communication  de la FRAO",
    "slug": "/document-de-communication-de-la-frao",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "La FRAO vient de finaliser son cinquième plan stratégique quinquennal (PSQ5) qui couvre la période 2016-2020.\nDans le...",
    "read_time_min": 7
  },
  {
    "id": 1221,
    "title": "Atelier de formation FRAO-AIDR",
    "slug": "/atelier-de-formation-frao-aidr",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/leader1.jpg",
    "excerpt": "A la demande de l’Alliance Internationale de Développement et de Recherches (AIDR), La Fondation Rurale de l’Afrique de...",
    "read_time_min": 7
  },
  {
    "id": 1217,
    "title": "Evaluation du Projet « Jeunes Actifs pour le Développement Urbain à Dakar » de Plan Sénégal (20 janvier 2017)",
    "slug": "/evaluation-du-projet-jeunes-actifs-pour-le-developpement-urbain-a-dakar-de-plan-senegal-20-janvier-2017",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "La Fondation Rurale de l’Afrique de l’Ouest (FRAO) a procédé à l’évaluation de la deuxième phase du projet « Jeunes...",
    "read_time_min": 2
  },
  {
    "id": 1212,
    "title": "Conceptualisation du Programme d'Urgence de Développement Communautaire au Sénégal (PUDC) (31 janvier 2017)",
    "slug": "/conceptualisation-du-programme-durgence-de-developpement-communautaire-au-senegal-pudc-31-janvier-2017",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Dans le cadre du contrat avec le bureau du PNUD au Sénégal, la FRAO a entrepris une étude visant à documenter le cadre...",
    "read_time_min": 7
  },
  {
    "id": 1207,
    "title": "Conseil des Gouverneurs",
    "slug": "/conseil-des-gouverneurs",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Genre",
    "image": "assets/image1.jpg",
    "excerpt": "Deux journées d'échanges entre la Fondation et ses Gouverneurs originaires du Togo, de la Guinée, du Ghana, du Sénégal...",
    "read_time_min": 3
  },
  {
    "id": 1176,
    "title": "Contrat d’assistance technique FRAO/PD-PAC",
    "slug": "/contrat-dassistance-technique-fraopd-pac",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/cassava.jpg",
    "excerpt": "Dans le cadre du processus de démarrage du Projet de Développement de la Pêche et de l’Aquaculture Continentale...",
    "read_time_min": 8
  },
  {
    "id": 1173,
    "title": "Rencontre FRAO-KKGB",
    "slug": "/rencontre-frao-kkgb",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "La FRAO a reçu ce 24 avril 2017, la visite des Maires de Kouar en la personne de Monsieur Baganda Sakho et celui de...",
    "read_time_min": 4
  },
  {
    "id": 1169,
    "title": "Rencontre FRAO- ADENA",
    "slug": "/rencontre-frao-adena",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/leader1.jpg",
    "excerpt": "La FRAO a reçu ce vendredi 28 avril 2017, la visite de Mr Moustapha DIA président de ADENA (Association pour le...",
    "read_time_min": 6
  },
  {
    "id": 1165,
    "title": "Convention de collaboration FRAO- KKGB (juin 2017)",
    "slug": "/convention-de-collaboration-frao-kkgb-juin-2017",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "La FRAO et l'Association Inter communale KKGB Dr Louis Jannel (Kothiary, Kouar, Goumbayel et Balla) ont signé le 06...",
    "read_time_min": 8
  },
  {
    "id": 1156,
    "title": "Atelier de lancement de projet (GAMBIE)",
    "slug": "/atelier-de-lancement-de-projet-gambie",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Atelier de lancement du projet « Promoting Interaction Platforms For Sustainable Agricultural Value Chain Development...",
    "read_time_min": 5
  },
  {
    "id": 1144,
    "title": "Signature de contrat FRAO-KOICA (février 2018)",
    "slug": "/signature-de-contrat-frao-koica-fevrier-2018",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/image1.jpg",
    "excerpt": "La Fondation Rurale de l’Afrique de l’Ouest (FRAO) a signé un contrat de deux (02) ans avec l’Agence Sud Coréenne de...",
    "read_time_min": 6
  },
  {
    "id": 974,
    "title": "Panel organisé par la caisse de solidarité des femmes de Nianing.",
    "slug": "/panel-organise-par-la-caisse-de-solidarite-des-femmes-de-nianing",
    "date": "11 Jan 2018",
    "year": "2018",
    "category": "Genre",
    "image": "assets/cassava.jpg",
    "excerpt": "Un panel sous le thème: La gestion durable des ressources halieutiques face aux impacts des changements climatiques:...",
    "read_time_min": 3
  },
  {
    "id": 971,
    "title": "Formation en Gestion des Savoirs",
    "slug": "/formation-en-gestion-des-savoirs",
    "date": "11 Jan 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/tof10.jpg",
    "excerpt": "Vous êtes Coordonnateurs ou Chefs d’équipe de projets, Chargé de la communication et/ou de la gestion des savoirs,...",
    "read_time_min": 2
  },
  {
    "id": 964,
    "title": "Projet de promotion dans les zones d'intervention de NEMA",
    "slug": "/projet-de-promotion-dans-les-zones-dintervention-de-nema",
    "date": "10 Jan 2018",
    "year": "2018",
    "category": "Genre",
    "image": "assets/leader1.jpg",
    "excerpt": "La Fondation Rurale de l'Afrique de l'Ouest (FRAO) en partenariat avec le National Agricultural Land and Water...",
    "read_time_min": 5
  },
  {
    "id": 943,
    "title": "Atelier de Validation",
    "slug": "/atelier-de-validation",
    "date": "02 Jan 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "A valider : Formation des agents de santé communautaires, Mise en œuvre des plans d'actions des plateformes, Séances...",
    "read_time_min": 7
  }
];
