const actualitesData = [
  {
    "id": 4006,
    "title": "Mballing : la FRAO accompagne la structuration d'une coopérative féminine de mangues séchées",
    "slug": "/mballing-mission-mars-2026-cooperative-feminine",
    "date": "24 Mars 2026",
    "year": "2026",
    "category": "Genre",
    "image": "assets/mballing-3.jpeg",
    "excerpt": "Les 23 et 24 mars 2026, la FRAO a conduit une mission à Mballing, dans la commune rurale de Malicounda, pour accompagner 17 femmes fondatrices d'une future coopérative dédiée à la transformation et la commercialisation de mangues séchées.",
    "read_time_min": 5,
    "full_content": "<h2>Une mission de terrain pour transformer une opportunité saisonnière en filière durable</h2><p>Les 23 et 24 mars 2026, la <strong>Fondation Rurale de l'Afrique de l'Ouest (FRAO)</strong> a conduit une mission de deux jours à Mballing, dans la commune rurale de Malicounda. Objectif : accompagner la structuration d'une coopérative féminine dédiée à la transformation et à la commercialisation de mangues séchées, en valorisant un fruit saisonnier dont les pertes post-récolte dépassent 40 % dans la zone.</p><figure><img src=\"assets/mballing-3.jpeg\" alt=\"Mangues séchées préparées par les femmes de Mballing\"><figcaption>Atelier de séchage des mangues : étape clé de la chaîne de valeur portée par les femmes fondatrices.</figcaption></figure><h3>Un programme de rencontres ciblées</h3><p>La mission s'est articulée autour de plusieurs rencontres clés. Une première séance avec l'<strong>AEPN</strong> a permis de planifier les activités malgré les contraintes budgétaires identifiées. Une seconde rencontre, plus dense, a réuni les <strong>17 femmes fondatrices</strong> issues de l'association « Un cartable pour toutes », porteuses du projet de coopérative.</p><p>Les discussions ont couvert un éventail large mais cohérent de sujets opérationnels :</p><ul><li>la <strong>structuration juridique</strong> de la future coopérative ;</li><li>les <strong>techniques de séchage solaire</strong> adaptées au climat sahélien ;</li><li>les exigences d'<strong>hygiène</strong> et la voie vers la <strong>certification HACCP</strong> ;</li><li>la conception de <strong>séchoirs solaires</strong> performants.</li></ul><figure><img src=\"assets/mballing-4.jpeg\" alt=\"Femmes du groupement préparant les mangues\"><figcaption>Préparation des mangues fraîches par le groupement de femmes — étape préalable au séchage.</figcaption></figure><h3>Des partenariats techniques de premier plan</h3><p>Pour ancrer le projet dans une dynamique d'excellence technique, la FRAO a sollicité deux institutions de référence : l'<strong>Institut de Technologie Alimentaire (ITA)</strong> pour la formation et la certification HACCP, ainsi que l'<strong>École Polytechnique de Dakar</strong> pour la conception et la fabrication des séchoirs solaires. Ces partenariats garantissent à la fois la qualité sanitaire des produits et l'autonomie technologique des bénéficiaires.</p><h3>Une feuille de route ambitieuse</h3><p>L'initiative cible à terme l'<strong>autonomisation économique de 50 femmes</strong> de Mballing, avec une extension prévue dès 2027 vers les villages voisins de <strong>Warang</strong> et <strong>Nianing</strong>. Les perspectives à court terme incluent la finalisation des partenariats techniques et la mobilisation de financements complémentaires auprès de la <strong>Ville et Métropole de Lyon</strong> et de <strong>La Guilde</strong>.</p><figure><img src=\"assets/mballing-5.jpeg\" alt=\"Gamme de produits transformés à base de mangue\"><figcaption>Diversification de la gamme : mangue séchée, conserve, jus de mangue-citron et autres déclinaisons.</figcaption></figure><h3>Recommandations issues de la mission</h3><p>Deux recommandations majeures ont émergé à l'issue des deux journées :</p><ol><li>l'<strong>élaboration d'un calendrier opérationnel</strong> détaillant la mise en place progressive de la coopérative ;</li><li>l'<strong>amélioration des conditions logistiques d'accueil</strong> lors des prochaines rencontres, gage de qualité du dialogue avec les bénéficiaires.</li></ol><blockquote><p>« Cette mission marque une étape décisive dans la mise en place d'un projet pilote d'autonomisation féminine, porteur de transformation économique locale par la valorisation des fruits saisonniers. »</p></blockquote><h2>Et après ?</h2><p>Les prochains mois seront consacrés à la formalisation juridique de la coopérative, à l'installation des séchoirs solaires conçus avec l'École Polytechnique, et au lancement d'une production pilote en vue d'un premier test commercial sur les marchés de Mbour et de Dakar. La FRAO assurera un suivi rapproché pour consolider les acquis et préparer la phase d'extension vers Warang et Nianing.</p>"
  },
  {
    "id": 4005,
    "title": "Banaba/Lac Rose : la FRAO impulse une nouvelle dynamique de microfinance avec Better World",
    "slug": "/microfinance-banaba-lac-rose-better-world",
    "date": "Sept 2025",
    "year": "2025",
    "category": "Agriculture",
    "image": "assets/bonaba-4.jpeg",
    "excerpt": "En partenariat avec l'ONG sud-coréenne Better World, la FRAO a animé une formation intensive de quatre jours à Banaba/Lac Rose, réunissant 40 membres de la coopérative Agricom et débouchant sur la mise en place d'un comité de microcrédit de 12 membres.",
    "read_time_min": 4,
    "full_content": "<h2>Un partenariat sud-coréen au service des coopératives sénégalaises</h2><p>En partenariat avec l'ONG <strong>Better World</strong>, organisation sud-coréenne intervenant au Sénégal depuis une décennie, la <strong>Fondation Rurale de l'Afrique de l'Ouest (FRAO)</strong> a animé une formation intensive sur la microfinance à Banaba, dans la zone du Lac Rose. La session a réuni <strong>40 membres — femmes et jeunes</strong> — de la société coopérative <strong>Agricom de Bonaba/Lac Rose</strong>, témoignant d'une mobilisation forte autour des enjeux financiers ruraux.</p><figure><img src=\"assets/bonaba-3.jpeg\" alt=\"Bannière du projet de développement agricole à Bonaba avec le partenariat KOICA\"><figcaption>Le projet, soutenu par KOICA et Better World, s'inscrit dans une dynamique de coopération sud-coréenne en faveur du développement rural sénégalais.</figcaption></figure><h3>Quatre jours pour bâtir des compétences durables</h3><p>Pendant <strong>quatre journées intensives</strong>, les participants ont parcouru un programme structuré et progressif. Au menu : les principes fondamentaux de la microfinance, les outils de gestion administrative et financière, ainsi que les mécanismes de prévention et de gestion des risques. La pédagogie a délibérément combiné apports théoriques, <strong>tests d'évaluation</strong>, <strong>cas pratiques</strong> et <strong>échanges interactifs</strong>, permettant à chacun d'ancrer les acquis dans les réalités du terrain.</p><figure><img src=\"assets/bonaba-4.jpeg\" alt=\"Session de formation avec présentation projetée et tableaux de restitution\"><figcaption>Travaux de groupe et restitutions collectives ont rythmé les quatre jours de formation.</figcaption></figure><h3>Vers une gouvernance financière transparente</h3><p>À l'issue de la formation, la FRAO a facilité la mise en place d'un <strong>comité de microcrédit composé de 12 membres</strong>. Structuré en commissions spécialisées, ce comité est désormais chargé :</p><ul><li>d'<strong>étudier les demandes de prêts</strong> de manière objective et participative ;</li><li>de <strong>définir les modalités d'octroi</strong> selon des critères transparents ;</li><li>d'assurer le <strong>suivi des remboursements</strong> dans un cadre responsable et collectif.</li></ul><figure><img src=\"assets/bonaba-5.jpeg\" alt=\"Membres de la coopérative Agricom assistant à la session de restitution\"><figcaption>Une mobilisation communautaire forte autour de la coopérative Agricom de Bonaba.</figcaption></figure><blockquote><p>« Cette initiative marque une avancée majeure pour la coopérative Agricom de Bonaba et illustre le rôle central de la FRAO dans le renforcement des capacités locales et la promotion d'une gouvernance financière durable au service des communautés rurales. »</p></blockquote><h3>Un modèle reproductible pour la sous-région</h3><p>Le dispositif déployé à Banaba/Lac Rose constitue un <strong>modèle reproductible</strong> pour d'autres coopératives agricoles de la zone sahélienne. La combinaison d'une formation rigoureuse, d'un appui à la structuration institutionnelle et d'un partenariat technique avec un acteur international comme Better World offre une formule équilibrée, ancrée dans les besoins locaux mais ouverte sur les standards internationaux de la finance inclusive.</p><p>La FRAO entend désormais capitaliser sur cette expérience pour soutenir d'autres coopératives partenaires, tout en assurant un accompagnement de proximité du comité de microcrédit nouvellement installé. Les premiers cycles d'octroi de prêts feront l'objet d'un suivi rapproché afin d'affiner les procédures et de documenter les bonnes pratiques pour essaimage.</p>"
  },
  {
    "id": 4004,
    "title": "Aviculture ouest-africaine : la FRAO anime un atelier stratégique pour structurer la filière",
    "slug": "/atelier-strategique-aviculture-ouest-africaine-2025",
    "date": "01 Juil 2025",
    "year": "2025",
    "category": "Agriculture",
    "image": "assets/aviculture-1.jpeg",
    "excerpt": "Le 1er juillet 2025 au Centre National Avicole de Mbao, la FRAO — par la voix du Pr Cheikh Ly — a animé un atelier réunissant les acteurs de l'IPAS pour cartographier la filière, vulgariser la SDAR et tracer une feuille de route régionale ouest-africaine.",
    "read_time_min": 6,
    "full_content": "<h2>Un atelier décisif pour l'avenir de l'aviculture ouest-africaine</h2><p>Le <strong>1er juillet 2025</strong>, l'<strong>Interprofession des acteurs de la filière avicole du Sénégal (IPAS)</strong> a organisé un atelier d'échanges consacré à la cartographie des acteurs nationaux et aux perspectives de création d'une <strong>plateforme multi-acteurs régionale</strong> pour les filières avicoles ouest-africaines. Animée par le <strong>Professeur Cheikh Ly</strong> de la Fondation Rurale de l'Afrique de l'Ouest (FRAO), la rencontre s'est tenue au <strong>Centre National Avicole (CNA) de Mbao</strong>.</p><figure><img src=\"assets/aviculture-1.jpeg\" alt=\"Travaux en plénière à l'atelier IPAS-FRAO-CNA au CNA de Mbao\"><figcaption>Plénière d'ouverture au Centre National Avicole de Mbao, sous l'animation du Pr Cheikh Ly (FRAO).</figcaption></figure><h3>Un secteur en pleine mutation</h3><p>L'aviculture, segment clé du sous-secteur de l'élevage, connaît un essor remarquable en Afrique de l'Ouest et au Sahel. Elle joue un <strong>rôle économique, nutritionnel et culturel majeur</strong>, mais reste encore loin de satisfaire la demande régionale en produits de volaille. Les défis structurels sont nombreux :</p><ul><li>déficit de financements adaptés à la filière ;</li><li>dépendance persistante aux <strong>intrants importés</strong> ;</li><li>faiblesse des <strong>échanges régionaux intra-africains</strong> ;</li><li>absence d'une stratégie publique régionale claire et coordonnée.</li></ul><h3>Trois sessions, trois ambitions</h3><p>Sous l'animation de la FRAO, l'atelier a permis de dresser un état des lieux précis de la filière avicole sénégalaise et d'ouvrir le débat sur son avenir régional. <strong>Trois sessions</strong> ont rythmé la journée, chacune apportant des éclairages et des propositions concrètes.</p><figure><img src=\"assets/aviculture-2.jpeg\" alt=\"Participante prenant part aux travaux en commission\"><figcaption>Travaux en commission : enrichissement collaboratif de la cartographie des acteurs.</figcaption></figure><p><strong>Session 1 — Cartographie des acteurs.</strong> La présentation de la cartographie nationale a donné lieu à un travail collaboratif d'actualisation : les participants ont enrichi le document en y ajoutant les nouvelles entités actives et en retirant les structures inactives, confirmant ainsi la vitalité — mais aussi la mouvance permanente — du secteur.</p><p><strong>Session 2 — Stratégie de Développement de l'Aviculture Rurale (SDAR).</strong> Élaborée en 2024 et déjà <strong>vulgarisée dans 12 régions</strong>, la SDAR a été présentée et discutée. Les échanges ont souligné l'importance d'intégrer pleinement l'<strong>aviculture familiale rurale</strong> dans la dynamique nationale, tout en fixant des priorités opérationnelles : <strong>digitalisation du suivi de production</strong> et <strong>finalisation de la stratégie IPAS 2025-2029</strong>.</p><p><strong>Session 3 — Feuille de route régionale.</strong> La dernière session a débouché sur des engagements concrets : création d'une <strong>task force ouest-africaine</strong>, adoption rapide du <strong>plan stratégique de l'IPAS</strong>, et mise en place d'une <strong>plateforme multi-acteurs</strong> inspirée du modèle sénégalais.</p><figure><img src=\"assets/aviculture-3.jpeg\" alt=\"Participants à l'atelier IPAS-FRAO-CNA\"><figcaption>Diversité des profils représentés : éleveurs, organisations professionnelles, services techniques de l'État et partenaires.</figcaption></figure><h3>Des recommandations fortes pour transformer la filière</h3><p>Les discussions ont abouti à un faisceau de recommandations majeures :</p><ul><li><strong>réviser la réglementation</strong> sectorielle pour l'adapter aux réalités contemporaines ;</li><li>développer des <strong>fermes agréées de production de poussins (OAC)</strong> ;</li><li>renforcer l'<strong>aviculture villageoise</strong>, levier de souveraineté alimentaire ;</li><li>promouvoir le <strong>poulet label</strong> pour conquérir les marchés de niche ;</li><li>consolider la <strong>coopération public-privé</strong> au service de la filière.</li></ul><p>Les participants ont également insisté sur la nécessité d'une <strong>diplomatie avicole active</strong>, capable de porter la voix de la filière dans les enceintes régionales et continentales.</p><blockquote><p>« En animant cet atelier, la FRAO a joué un rôle central dans la mobilisation des acteurs et la définition d'une vision commune. L'urgence est désormais de structurer la filière à l'échelle régionale pour répondre aux enjeux de sécurité alimentaire, d'intégration économique et de création d'emplois. »</p></blockquote><h3>Une dynamique régionale en marche</h3><p>L'atelier du 1er juillet 2025 marque une <strong>étape charnière</strong> pour la filière avicole ouest-africaine. La FRAO entend capitaliser sur ce momentum pour faire émerger une plateforme multi-acteurs effective, articulée avec les politiques publiques nationales et avec les organisations régionales d'intégration. Les prochains mois seront décisifs pour traduire les engagements pris en actions concrètes — au bénéfice des éleveurs, des consommateurs et de la souveraineté alimentaire de la sous-région.</p>"
  },
  {
    "id": 3254,
    "title": "Atelier d’information et de sensibilisation sur les Coopératives du 24 au 26 Juillet 2024 à Bonaba avec l’ONG BETTER WORLD",
    "slug": "/atelier-dinformation-et-de-sensibilisation-sur-les-cooperatives-du-24-au-26-juillet-2024-a-bonaba-avec-long-better-world",
    "date": "08 Oct 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/leader1.jpg",
    "excerpt": "Atelier avec les leaders des associations, du GIE et avec les femmes et les jeunes\nTournée d’information et de...",
    "read_time_min": 4
  },
  {
    "id": 3237,
    "title": "Atelier au King Fahd Palace le 17 Avril 2024",
    "slug": "/atelier-au-king-fahd-palace-le-17-avril-2024",
    "date": "01 Oct 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "Le forum de partage et d’échanges avec les jeunes a pour objectif de présenter les réalisations et effet des...",
    "read_time_min": 6
  },
  {
    "id": 3229,
    "title": "Enquêtes sur l'engagement des Associations et du GIE",
    "slug": "/enquetes-sur-lengagement-des-associations-et-du-gie",
    "date": "30 Sep 2024",
    "year": "2024",
    "category": "Gouvernance",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Enquêtes sur l’engagement des Associations et du GIE à mettre en place une Coopérative du 07 au 13 Août 2024 a...",
    "read_time_min": 3
  },
  {
    "id": 3221,
    "title": "Atelier de partage et de consolidation des Résultats d’ADOS aux Résidences Mamoune",
    "slug": "/atelier-de-partage-et-de-consolidation-des-resultats-dados-aux-residences-mamoune",
    "date": "30 Sep 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/image1.jpg",
    "excerpt": "PROGRAMME ADOS : Amélioration de la Santé de la Reproduction des Adolescentes au SénégalAtelier de partage et de...",
    "read_time_min": 4
  },
  {
    "id": 3217,
    "title": "Atelier d’élaboration des Produits de Connaissances pour le Partage des résultats du Programme ADOS Hôtel Onomo du 18 au 19 Mars 2024",
    "slug": "/atelier-delaboration-des-produits-de-connaissances-pour-le-partage-des-resultats-du-programme-ados",
    "date": "28 Sep 2024",
    "year": "2024",
    "category": "Partenariat",
    "image": "assets/cassava.jpg",
    "excerpt": "Cet atelier a pour objectifs de sélectionner les thèmes pour alimenter les premiers produits de connaissances ;...",
    "read_time_min": 6
  },
  {
    "id": 3026,
    "title": "cooperation between FRAO and SNU.",
    "slug": "/cooperation-between-frao-and-snu",
    "date": "24 Août 2023",
    "year": "2023",
    "category": "Genre",
    "image": "assets/tof10.jpg",
    "excerpt": "FRAO/WARF and Seoul National University.\nFRAO/WARF continues its partnership with Koica and Korean organizations. In...",
    "read_time_min": 8
  },
  {
    "id": 3022,
    "title": "Nouveau Conseil des Gouverneurs.",
    "slug": "/nouveau-conseil-des-gouverneurs",
    "date": "24 Août 2023",
    "year": "2023",
    "category": "Genre",
    "image": "assets/leader1.jpg",
    "excerpt": "La FRAO/WARF s'est dotée d'un nouveau Conseil des Gouverneurs (CG) en Février 2023. Ce changement fait suite à...",
    "read_time_min": 8
  },
  {
    "id": 2911,
    "title": "Agricultural Value Chain Interaction Platforms (AVIP)",
    "slug": "/agricultural-value-chain-interaction-platforms-avip",
    "date": "23 Nov 2021",
    "year": "2021",
    "category": "Climat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "To have more /click on the link below\nAgricultural Value Chain Interaction Platforms (AVIP)",
    "read_time_min": 3
  },
  {
    "id": 2824,
    "title": "Formation en «Gestion Administrative et Financière » des bénéficiaires du Projet de Développement communautaire de Better World à Bonaba",
    "slug": "/la-formation-en-gestion-administrative-et-financiere-des-beneficiaires-du-projet-de-developpement-communautaire-de-better-world-a-bonaba",
    "date": "17 Nov 2021",
    "year": "2021",
    "category": "Agriculture",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Du 04 au 06 octobre, s’est tenu une formation en «Gestion Administrative et Financière» organisée par l’ONG Better...",
    "read_time_min": 8
  },
  {
    "id": 2741,
    "title": "Agricultural Value Chain Interaction Platforms (AVIP) for Sustainable Access to Markets",
    "slug": "/agricultural-value-chain-interaction-platforms-avip-for-sustainable-access-to-markets",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Agriculture",
    "image": "assets/image1.jpg",
    "excerpt": "The ROOTS project, with implementation support from West Africa Rural Foundation, has initiated work on the...",
    "read_time_min": 7
  },
  {
    "id": 2728,
    "title": "Resilience of Organizations for Transformative Smallholder Agriculture Project (ROOTS)",
    "slug": "/resilience-of-organizations-for-transformative-smallholder-agriculture-project-roots",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Climat",
    "image": "assets/cassava.jpg",
    "excerpt": "The International Fund for Agricultural Development (IFAD) is supporting The Government of the Gambia to implement the...",
    "read_time_min": 8
  },
  {
    "id": 2725,
    "title": "Formation en « Dynamique Organisationnelle » des bénéficiaires du Projet de Développement communautaire de Better World à Bonaba",
    "slug": "/formation-en-dynamique-organisationnelle-des-beneficiaires-du-projet-de-developpement-communautaire-de-better-world-a-bonaba",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "24 bénéficiaires ont pris part aux trois jours de formation, organisés à l’intention des leaders du Groupement...",
    "read_time_min": 5
  },
  {
    "id": 2674,
    "title": "Collaboration entre la FRAO et BETTER WORLD pour le renforcement des capacités des bénéficiaires du Projet de Développement Communautaire à Bonaba)",
    "slug": "/collaboration-entre-la-frao-et-better-world-pour-le-renforcement-des-capacites-des-beneficiaires-du-projet-de-developpement-communautaire-a-bonaba",
    "date": "16 Nov 2021",
    "year": "2021",
    "category": "Gouvernance",
    "image": "assets/leader1.jpg",
    "excerpt": "Le 27 Août 2021, les deux institutions ont signé un contrat de prestation de service pour l’exécution de sessions de...",
    "read_time_min": 5
  },
  {
    "id": 2644,
    "title": "Nécrologie: Décès du Docteur Dominique Hounkonnou.",
    "slug": "/necrologie-deces-du-docteur-dominique-hounkonnou",
    "date": "24 Nov 2020",
    "year": "2020",
    "category": "Gouvernance",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": ".",
    "read_time_min": 2
  },
  {
    "id": 2445,
    "title": "Visite d’échange des bénéficiaires du projet AVIP dans la vallée du fleuve Sénégal",
    "slug": "/visite-dechange-des-beneficiaires-du-projet-avip-dans-la-vallee-du-fleuve-senegal",
    "date": "14 Nov 2019",
    "year": "2019",
    "category": "Genre",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "La FRAO, depuis 2018, est l’acteur principal de la mise en œuvre du projet « Agricultural Value Chain Interaction...",
    "read_time_min": 2
  },
  {
    "id": 2439,
    "title": "Formation sur les plateformes d’interaction de la chaîne de valeur riz",
    "slug": "/formation-sur-les-plateformes-dinteraction-de-la-chaine-de-valeur-riz",
    "date": "11 Sep 2019",
    "year": "2019",
    "category": "Climat",
    "image": "assets/image1.jpg",
    "excerpt": "La FRAO a initié une série d’ateliers de formation sur les plateformes d’interaction de la chaine de valeur riz au...",
    "read_time_min": 6
  },
  {
    "id": 2380,
    "title": "Nouveau membre du staff programme .",
    "slug": "/nouveau-membre-du-staff-programme",
    "date": "02 Juil 2019",
    "year": "2019",
    "category": "Gouvernance",
    "image": "assets/cassava.jpg",
    "excerpt": "Serigne Tacko Kandji est titulaire d'un diplôme d'ingénieur agronome et d'un doctorat en agro-écologie.\nIl travaille en...",
    "read_time_min": 8
  },
  {
    "id": 2336,
    "title": "Pot de départ à la retraite",
    "slug": "/pot-de-depart-a-la-retraite",
    "date": "15 Juin 2019",
    "year": "2019",
    "category": "Agriculture",
    "image": "assets/tof10.jpg",
    "excerpt": "Le Conseil des Gouverneurs de la FRAO ainsi que sa Direction Exécutive ont rendu un vibrant hommage à Mme THIAM pour...",
    "read_time_min": 2
  },
  {
    "id": 2325,
    "title": "Activités de renforcement de capacités du mois de février 2019",
    "slug": "/activites-de-renforcement-de-capacites-du-mois-de-fevrier-2019",
    "date": "08 Avr 2019",
    "year": "2019",
    "category": "Gouvernance",
    "image": "assets/leader1.jpg",
    "excerpt": "Conformément au document de référence, la FRAO poursuit la mise en œuvre de l’an II du Projet relatif aux chaînes de...",
    "read_time_min": 3
  },
  {
    "id": 2270,
    "title": "Atelier à mi-parcours",
    "slug": "/atelier-a-mi-parcours",
    "date": "26 Fév 2019",
    "year": "2019",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "Cet atelier organisé, par la FRAO le 26 janvier 2019 dernier, avait pour objectif d’évaluer la mise en œuvre de la...",
    "read_time_min": 5
  },
  {
    "id": 2242,
    "title": "Journées d’échange et de dégustation  « Field Day »",
    "slug": "/journees-dechange-et-de-degustation-field-day",
    "date": "22 Jan 2019",
    "year": "2019",
    "category": "Agriculture",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Le « Field Day » est l’aboutissement des premières activités agronomiques mises en œuvre dans le cadre du Projet de...",
    "read_time_min": 2
  },
  {
    "id": 2199,
    "title": "Les premières récoltes de riz",
    "slug": "/les-premieres-recoltes-de-riz",
    "date": "05 Déc 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/image1.jpg",
    "excerpt": "Les récoltes dans les parcelles de démonstration rizicoles de Pendao 3 et de Dimath (Zone d'intervention du Projet de...",
    "read_time_min": 8
  },
  {
    "id": 2126,
    "title": "Sessions de Formation en « Irrigation et Protection des Cultures »",
    "slug": "/sessions-de-formation-en-irrigation-et-protection-des-cultures",
    "date": "04 Déc 2018",
    "year": "2018",
    "category": "Climat",
    "image": "assets/cassava.jpg",
    "excerpt": "Il s’agit de la troisième session de formation agronomique au profit des bénéficiaires du Projet de Développement...",
    "read_time_min": 4
  },
  {
    "id": 2115,
    "title": "Ateliers de formation sur la « Gouvernance dans la gestion d’un GIE »",
    "slug": "/ateliers-de-formation-sur-la-gouvernance-dans-la-gestion-dun-gie",
    "date": "19 Oct 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "Ces ateliers sont organisés par la FRAO à l’intention des Groupements d’Intérêt Economique (GIE) bénéficiaires du...",
    "read_time_min": 3
  },
  {
    "id": 2009,
    "title": "Ateliers de formation sur «l’Entretien des cultures du riz »",
    "slug": "/ateliers-de-formation-sur-lentretien-des-cultures-du-riz-2",
    "date": "11 Oct 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/leader1.jpg",
    "excerpt": "Ces ateliers sont organisés à la suite de la formation sur la Préparation d’une campagne rizicole et l’installation des...",
    "read_time_min": 8
  },
  {
    "id": 1995,
    "title": "Ateliers de formation sur les Techniques de Production Améliorées: Préparation de campagne et Installation des cultures",
    "slug": "/ateliers-de-formation-sur-les-techniques-de-production-ameliorees-preparation-de-campagne-et-installation-des-cultures",
    "date": "28 Sep 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "Dans le but de permettre aux producteurs d’améliorer leurs techniques de production rizicole, trois ateliers de...",
    "read_time_min": 8
  },
  {
    "id": 1988,
    "title": "Ateliers de formation en « Gestion Administrative et Financière des GIE »",
    "slug": "/ateliers-de-formation-en-gestion-administrative-et-financiere-des-gie",
    "date": "28 Sep 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "La FRAO a animé trois (03) ateliers de formation en « Gestion Administrative et Financière » dans le cadre de la mise...",
    "read_time_min": 3
  },
  {
    "id": 1983,
    "title": "Formation en « Dynamique Organisationnelle » des GIE et Unions bénéficiaires du Projet de Développement Durable et Inclusif de la Chaîne de Valeur Riz à Podor.",
    "slug": "/formation-en-dynamique-organisationnelle-des-gie-et-unions-beneficiaire-du-projet-de-developpement-durable-et-inclusif-de-la-chaine-de-valeur-riz-a-podor",
    "date": "28 Sep 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/image1.jpg",
    "excerpt": "La FRAO est responsable de la mise en œuvre du volet renforcement de capacités des Organisations Paysannes...",
    "read_time_min": 2
  },
  {
    "id": 1965,
    "title": "Ateliers de lancement communautaire du Projet de Développement Durable et Inclusif de Chaine de Valeur Riz à Podor",
    "slug": "/ateliers-de-lancement-communautaire-du-projet-de-developpement-durable-et-inclusif-de-chaine-de-valeur-riz-a-podor",
    "date": "18 Sep 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/cassava.jpg",
    "excerpt": "Pour l’opérationnalisation des activités du projet de Développement Durable et Inclusif de Chaine de Valeur Riz à...",
    "read_time_min": 7
  },
  {
    "id": 1855,
    "title": "Nécrologie : Une ancienne membre du Conseil des gouverneurs de la FRAO décédée",
    "slug": "/necrologie-une-ancienne-membre-du-conseil-des-gouverneurs-de-la-frao-decedee",
    "date": "09 Juil 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/tof10.jpg",
    "excerpt": "Hommage à une Militante\ndu développement durable et de l’autonomisation\ndes femmes en Afrique : Madame Diana Lima...",
    "read_time_min": 4
  },
  {
    "id": 1845,
    "title": "CONVENTION    DE    COLLABORATION FRAO- Fédération des Associations du Xer (FAX)",
    "slug": "/convention-de-collaboration-frao-federation-des-associations-du-xer-fax",
    "date": "05 Juil 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/leader1.jpg",
    "excerpt": "La FRAO, fidèle à sa mission de contribuer à résoudre les problèmes des sociétés rurales africaines, en appuyant les...",
    "read_time_min": 3
  },
  {
    "id": 1272,
    "title": "PARTENARIAT avec la FONDATION 2iE (Institut International d’Ingénierie de l’Eau et de l’Environnement)",
    "slug": "/partenariat-avec-la-fondation-2ie-institut-international-dingenierie-de-leau-et-de-lenvironnement",
    "date": "21 Fév 2018",
    "year": "2018",
    "category": "Climat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "La FRAO et la Fondation 2IE (Institut International d’Ingénierie de l’Eau et de l’Environnement) ont signé une...",
    "read_time_min": 6
  },
  {
    "id": 1243,
    "title": "Assistance technique au Ministère de la Pêche et de l’Aquaculture de (MPA) de la République du Congo.",
    "slug": "/assistance-technique-au-ministere-de-la-peche-et-de-laquaculture-de-mpa-de-la-republique-du-congo",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "La FRAO a signé un contrat d’assistance technique de huit (8) mois (Mai – Décembre 2016) pour le renforcement des...",
    "read_time_min": 2
  },
  {
    "id": 1239,
    "title": "Ateliers de formation du 2 au 6 mai 2016 – Accra, Ghana.",
    "slug": "/ateliers-de-formation-du-2-au-6-mai-2016-accra-ghana",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/image1.jpg",
    "excerpt": "Dans le cadre de l’Accord de Partenariat signé en Janvier 2015 avec Fondation 2iE Institut International d'Ingénierie...",
    "read_time_min": 2
  },
  {
    "id": 1230,
    "title": "Nouveau  Directeur Exécutif de la FRAO",
    "slug": "/nouveau-directeur-executif-de-la-frao",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/cassava.jpg",
    "excerpt": "Le Conseil des Gouverneurs de la Fondation, lors de sa session extraordinaire du 18 mars 2016, a retenu le Dr. Mohamed...",
    "read_time_min": 6
  },
  {
    "id": 1225,
    "title": "Document de communication  de la FRAO",
    "slug": "/document-de-communication-de-la-frao",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "La FRAO vient de finaliser son cinquième plan stratégique quinquennal (PSQ5) qui couvre la période 2016-2020.\nDans le...",
    "read_time_min": 7
  },
  {
    "id": 1221,
    "title": "Atelier de formation FRAO-AIDR",
    "slug": "/atelier-de-formation-frao-aidr",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/leader1.jpg",
    "excerpt": "A la demande de l’Alliance Internationale de Développement et de Recherches (AIDR), La Fondation Rurale de l’Afrique de...",
    "read_time_min": 7
  },
  {
    "id": 1217,
    "title": "Evaluation du Projet « Jeunes Actifs pour le Développement Urbain à Dakar » de Plan Sénégal (20 janvier 2017)",
    "slug": "/evaluation-du-projet-jeunes-actifs-pour-le-developpement-urbain-a-dakar-de-plan-senegal-20-janvier-2017",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "La Fondation Rurale de l’Afrique de l’Ouest (FRAO) a procédé à l’évaluation de la deuxième phase du projet « Jeunes...",
    "read_time_min": 2
  },
  {
    "id": 1212,
    "title": "Conceptualisation du Programme d'Urgence de Développement Communautaire au Sénégal (PUDC) (31 janvier 2017)",
    "slug": "/conceptualisation-du-programme-durgence-de-developpement-communautaire-au-senegal-pudc-31-janvier-2017",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Dans le cadre du contrat avec le bureau du PNUD au Sénégal, la FRAO a entrepris une étude visant à documenter le cadre...",
    "read_time_min": 7
  },
  {
    "id": 1207,
    "title": "Conseil des Gouverneurs",
    "slug": "/conseil-des-gouverneurs",
    "date": "20 Fév 2018",
    "year": "2018",
    "category": "Genre",
    "image": "assets/image1.jpg",
    "excerpt": "Deux journées d'échanges entre la Fondation et ses Gouverneurs originaires du Togo, de la Guinée, du Ghana, du Sénégal...",
    "read_time_min": 3
  },
  {
    "id": 1176,
    "title": "Contrat d’assistance technique FRAO/PD-PAC",
    "slug": "/contrat-dassistance-technique-fraopd-pac",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/cassava.jpg",
    "excerpt": "Dans le cadre du processus de démarrage du Projet de Développement de la Pêche et de l’Aquaculture Continentale...",
    "read_time_min": 8
  },
  {
    "id": 1173,
    "title": "Rencontre FRAO-KKGB",
    "slug": "/rencontre-frao-kkgb",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/tof10.jpg",
    "excerpt": "La FRAO a reçu ce 24 avril 2017, la visite des Maires de Kouar en la personne de Monsieur Baganda Sakho et celui de...",
    "read_time_min": 4
  },
  {
    "id": 1169,
    "title": "Rencontre FRAO- ADENA",
    "slug": "/rencontre-frao-adena",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/leader1.jpg",
    "excerpt": "La FRAO a reçu ce vendredi 28 avril 2017, la visite de Mr Moustapha DIA président de ADENA (Association pour le...",
    "read_time_min": 6
  },
  {
    "id": 1165,
    "title": "Convention de collaboration FRAO- KKGB (juin 2017)",
    "slug": "/convention-de-collaboration-frao-kkgb-juin-2017",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "La FRAO et l'Association Inter communale KKGB Dr Louis Jannel (Kothiary, Kouar, Goumbayel et Balla) ont signé le 06...",
    "read_time_min": 8
  },
  {
    "id": 1156,
    "title": "Atelier de lancement de projet (GAMBIE)",
    "slug": "/atelier-de-lancement-de-projet-gambie",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/PUDC-smaljpg.jpg",
    "excerpt": "Atelier de lancement du projet « Promoting Interaction Platforms For Sustainable Agricultural Value Chain Development...",
    "read_time_min": 5
  },
  {
    "id": 1144,
    "title": "Signature de contrat FRAO-KOICA (février 2018)",
    "slug": "/signature-de-contrat-frao-koica-fevrier-2018",
    "date": "16 Fév 2018",
    "year": "2018",
    "category": "Partenariat",
    "image": "assets/image1.jpg",
    "excerpt": "La Fondation Rurale de l’Afrique de l’Ouest (FRAO) a signé un contrat de deux (02) ans avec l’Agence Sud Coréenne de...",
    "read_time_min": 6
  },
  {
    "id": 974,
    "title": "Panel organisé par la caisse de solidarité des femmes de Nianing.",
    "slug": "/panel-organise-par-la-caisse-de-solidarite-des-femmes-de-nianing",
    "date": "11 Jan 2018",
    "year": "2018",
    "category": "Genre",
    "image": "assets/cassava.jpg",
    "excerpt": "Un panel sous le thème: La gestion durable des ressources halieutiques face aux impacts des changements climatiques:...",
    "read_time_min": 3
  },
  {
    "id": 971,
    "title": "Formation en Gestion des Savoirs",
    "slug": "/formation-en-gestion-des-savoirs",
    "date": "11 Jan 2018",
    "year": "2018",
    "category": "Agriculture",
    "image": "assets/tof10.jpg",
    "excerpt": "Vous êtes Coordonnateurs ou Chefs d’équipe de projets, Chargé de la communication et/ou de la gestion des savoirs,...",
    "read_time_min": 2
  },
  {
    "id": 964,
    "title": "Projet de promotion dans les zones d'intervention de NEMA",
    "slug": "/projet-de-promotion-dans-les-zones-dintervention-de-nema",
    "date": "10 Jan 2018",
    "year": "2018",
    "category": "Genre",
    "image": "assets/leader1.jpg",
    "excerpt": "La Fondation Rurale de l'Afrique de l'Ouest (FRAO) en partenariat avec le National Agricultural Land and Water...",
    "read_time_min": 5
  },
  {
    "id": 943,
    "title": "Atelier de Validation",
    "slug": "/atelier-de-validation",
    "date": "02 Jan 2018",
    "year": "2018",
    "category": "Gouvernance",
    "image": "assets/25Nairobi-Market.jpg",
    "excerpt": "A valider : Formation des agents de santé communautaires, Mise en œuvre des plans d'actions des plateformes, Séances...",
    "read_time_min": 7
  }
];
